
server:
  port:8080

rest:
  auth-open:true #如果为true则开启JWT的验证


jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  md5-key: randomKey      #md5加密混淆key

mybatis-plus:
  mapper-locations: classpath*:com/tang/zhen/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.tang.zhen: debug
  path: logs/
  file: next-film.log


film:
  img-pre: http://nextfilm.cn/

order:
  file-path-pre : E:/视频/享学vip/猫眼商城/课程资料（spring boot猫眼商城）/14-15 订单模块/resources/


